dist: jammy
language: node_js
node_js:
  - stable

addons:
  artifacts: true

install:
  - bash ./dev/download.sh

script:
  - bash ./dev/validate.sh
  - bash ./dev/publish.sh
  - cat package.json

deploy:
  provider: npm
  email: "nemanjan00@gmail.com"
  api_key: $NPM_TOKEN

